package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type sourceIndexSection struct {
	Domain       string
	RootSources  []sourceIndexEntry
	GroupIndexes []groupIndexEntry
}

type sourceIndexEntry struct {
	Title          string
	Path           string
	SourceType     string
	SyncPolicy     string
	DiscoveryState string
}

type groupIndexEntry struct {
	Title string
	Path  string
	Count int
	Owner string
}

func upsertSourcesRootIndex(vaultRoot string) error {
	sourcesDir := filepath.Join(vaultRoot, "02_sources")
	stubs, err := FindSourceStubs(sourcesDir)
	if err != nil {
		return err
	}

	sections := make(map[string]*sourceIndexSection)
	for _, absPath := range stubs {
		rel, err := filepath.Rel(sourcesDir, absPath)
		if err != nil {
			continue
		}
		rel = filepath.ToSlash(rel)
		if rel == "INDEX.md" {
			continue
		}

		parts := strings.Split(rel, "/")
		if len(parts) < 2 {
			continue
		}

		domain := parts[0]
		section := sections[domain]
		if section == nil {
			section = &sourceIndexSection{Domain: domain}
			sections[domain] = section
		}

		base := parts[len(parts)-1]
		if base == "INDEX.md" {
			if len(parts) == 2 {
				continue
			}
			title := readMarkdownTitle(absPath)
			if title == "" {
				title = filepath.Base(filepath.Dir(absPath))
			}
			section.GroupIndexes = append(section.GroupIndexes, groupIndexEntry{
				Title: title,
				Path:  rel,
				Count: countListedSourcesInIndex(absPath),
				Owner: parts[1],
			})
			continue
		}

		if len(parts) != 2 {
			continue
		}

		stub, err := ParseSourceStub(absPath)
		if err != nil || stub.Source != "notion" {
			continue
		}

		sourceType := stub.SourceType
		if sourceType == "" {
			sourceType = "page"
		}

		section.RootSources = append(section.RootSources, sourceIndexEntry{
			Title:          stub.Title,
			Path:           rel,
			SourceType:     sourceType,
			SyncPolicy:     stub.SyncPolicy,
			DiscoveryState: stub.DiscoveryState,
		})
	}

	var domains []string
	for domain := range sections {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		sort.Slice(sections[domain].RootSources, func(i, j int) bool {
			return strings.ToLower(sections[domain].RootSources[i].Title) < strings.ToLower(sections[domain].RootSources[j].Title)
		})
		sort.Slice(sections[domain].GroupIndexes, func(i, j int) bool {
			return strings.ToLower(sections[domain].GroupIndexes[i].Title) < strings.ToLower(sections[domain].GroupIndexes[j].Title)
		})
		if err := upsertDomainIndex(vaultRoot, sections[domain]); err != nil {
			return err
		}
	}

	indexPath := filepath.Join(sourcesDir, "INDEX.md")
	var sb strings.Builder
	sb.WriteString("# Sources Index\n\n")
	sb.WriteString("Auto-generated by `forge-sync sync-sources`.\n\n")
	sb.WriteString("Use the domain indexes below as the main entry points.\n\n")
	sb.WriteString("## Domains\n")
	if len(domains) == 0 {
		sb.WriteString("- (empty)\n")
	} else {
		for _, domain := range domains {
			section := sections[domain]
			target := filepath.Join(sourcesDir, domain, "INDEX.md")
			sb.WriteString(fmt.Sprintf("- %s — %d root source(s), %d group(s)\n", markdownLink(indexPath, target, prettyDomainTitle(domain)+" Sources"), len(section.RootSources), len(section.GroupIndexes)))
		}
	}
	sb.WriteString("\n")

	return os.WriteFile(indexPath, []byte(sb.String()), 0644)
}

func upsertDomainIndex(vaultRoot string, section *sourceIndexSection) error {
	sourcesDir := filepath.Join(vaultRoot, "02_sources")
	indexPath := filepath.Join(sourcesDir, section.Domain, "INDEX.md")
	if err := os.MkdirAll(filepath.Dir(indexPath), 0755); err != nil {
		return err
	}

	rootTitles := make(map[string]string)
	for _, entry := range section.RootSources {
		rootTitles[strings.TrimSuffix(filepath.Base(entry.Path), filepath.Ext(entry.Path))] = entry.Title
	}

	grouped := make(map[string][]groupIndexEntry)
	for _, entry := range section.GroupIndexes {
		grouped[entry.Owner] = append(grouped[entry.Owner], entry)
	}

	var ownerOrder []string
	for _, entry := range section.RootSources {
		key := strings.TrimSuffix(filepath.Base(entry.Path), filepath.Ext(entry.Path))
		if _, ok := grouped[key]; ok {
			ownerOrder = append(ownerOrder, key)
		}
	}
	var extras []string
	for owner := range grouped {
		if _, ok := rootTitles[owner]; ok {
			continue
		}
		extras = append(extras, owner)
	}
	sort.Slice(extras, func(i, j int) bool {
		return strings.ToLower(prettyDomainTitle(extras[i])) < strings.ToLower(prettyDomainTitle(extras[j]))
	})
	ownerOrder = append(ownerOrder, extras...)

	var sb strings.Builder
	sb.WriteString("# " + prettyDomainTitle(section.Domain) + " Sources\n\n")
	sb.WriteString("Auto-generated by `forge-sync sync-sources`.\n\n")

	sb.WriteString("## Root Sources\n")
	if len(section.RootSources) == 0 {
		sb.WriteString("- (none)\n")
	} else {
		for _, entry := range section.RootSources {
			target := filepath.Join(sourcesDir, filepath.FromSlash(entry.Path))
			line := fmt.Sprintf("- %s (`%s`, `%s`)", markdownLink(indexPath, target, entry.Title), entry.SourceType, entry.SyncPolicy)
			if entry.DiscoveryState == "stale" {
				line += " `[stale]`"
			}
			sb.WriteString(line + "\n")
		}
	}
	sb.WriteString("\n")

	sb.WriteString("## Groups By Source\n")
	if len(ownerOrder) == 0 {
		sb.WriteString("- (none)\n")
	} else {
		for _, owner := range ownerOrder {
			ownerTitle := rootTitles[owner]
			if ownerTitle == "" {
				ownerTitle = prettyDomainTitle(owner)
			}
			sb.WriteString("### " + ownerTitle + "\n")
			for _, entry := range grouped[owner] {
				target := filepath.Join(sourcesDir, filepath.FromSlash(entry.Path))
				sb.WriteString(fmt.Sprintf("- %s — %d item(s)\n", markdownLink(indexPath, target, entry.Title), entry.Count))
			}
			sb.WriteString("\n")
		}
	}

	return os.WriteFile(indexPath, []byte(sb.String()), 0644)
}

func readMarkdownTitle(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return ""
}

func countListedSourcesInIndex(indexPath string) int {
	f, err := os.Open(indexPath)
	if err != nil {
		return 0
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	inSources := false
	count := 0
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		switch {
		case line == "## Sources":
			inSources = true
			continue
		case strings.HasPrefix(line, "## ") && inSources:
			return count
		case !inSources:
			continue
		case line == "- (empty)":
			return 0
		case strings.HasPrefix(line, "- "):
			count++
		}
	}
	return count
}

func prettyDomainTitle(value string) string {
	parts := strings.Split(value, "-")
	for i, part := range parts {
		if part == "" {
			continue
		}
		if isASCIIAlphaNum(part) {
			parts[i] = strings.ToUpper(part[:1]) + strings.ToLower(part[1:])
		}
	}
	return strings.Join(parts, " ")
}

func isASCIIAlphaNum(s string) bool {
	for _, r := range s {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') {
			return false
		}
	}
	return s != ""
}
