package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type sourceIndexSection struct {
	Domain       string
	RootSources  []sourceIndexEntry
	GroupIndexes []groupIndexEntry
}

type sourceIndexEntry struct {
	Title          string
	Path           string
	SourceType     string
	SyncPolicy     string
	DiscoveryState string
}

type groupIndexEntry struct {
	Title string
	Path  string
	Count int
}

func upsertSourcesRootIndex(vaultRoot string) error {
	sourcesDir := filepath.Join(vaultRoot, "02_sources")
	stubs, err := FindSourceStubs(sourcesDir)
	if err != nil {
		return err
	}

	sections := make(map[string]*sourceIndexSection)
	for _, absPath := range stubs {
		rel, err := filepath.Rel(sourcesDir, absPath)
		if err != nil {
			continue
		}
		rel = filepath.ToSlash(rel)
		if rel == "INDEX.md" {
			continue
		}

		parts := strings.Split(rel, "/")
		if len(parts) < 2 {
			continue
		}

		domain := parts[0]
		section := sections[domain]
		if section == nil {
			section = &sourceIndexSection{Domain: domain}
			sections[domain] = section
		}

		base := parts[len(parts)-1]
		if base == "INDEX.md" {
			title := readMarkdownTitle(absPath)
			if title == "" {
				title = filepath.Base(filepath.Dir(absPath))
			}
			section.GroupIndexes = append(section.GroupIndexes, groupIndexEntry{
				Title: title,
				Path:  rel,
				Count: countDirectMarkdownChildren(filepath.Dir(absPath)),
			})
			continue
		}

		if len(parts) != 2 {
			continue
		}

		stub, err := ParseSourceStub(absPath)
		if err != nil || stub.Source != "notion" {
			continue
		}

		sourceType := stub.SourceType
		if sourceType == "" {
			sourceType = "page"
		}

		section.RootSources = append(section.RootSources, sourceIndexEntry{
			Title:          stub.Title,
			Path:           rel,
			SourceType:     sourceType,
			SyncPolicy:     stub.SyncPolicy,
			DiscoveryState: stub.DiscoveryState,
		})
	}

	var domains []string
	for domain := range sections {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	for _, domain := range domains {
		sort.Slice(sections[domain].RootSources, func(i, j int) bool {
			return strings.ToLower(sections[domain].RootSources[i].Title) < strings.ToLower(sections[domain].RootSources[j].Title)
		})
		sort.Slice(sections[domain].GroupIndexes, func(i, j int) bool {
			return strings.ToLower(sections[domain].GroupIndexes[i].Title) < strings.ToLower(sections[domain].GroupIndexes[j].Title)
		})
	}

	indexPath := filepath.Join(sourcesDir, "INDEX.md")
	var sb strings.Builder
	sb.WriteString("# Sources Index\n\n")
	sb.WriteString("Auto-generated by `forge-sync sync-sources`.\n\n")
	sb.WriteString("## Domains\n")
	if len(domains) == 0 {
		sb.WriteString("- (empty)\n")
	} else {
		for _, domain := range domains {
			anchor := strings.ToLower(domain)
			sb.WriteString(fmt.Sprintf("- [%s](#%s)\n", domain, anchor))
		}
	}
	sb.WriteString("\n")

	for _, domain := range domains {
		section := sections[domain]
		sb.WriteString("## " + domain + "\n\n")

		sb.WriteString("### Root Sources\n")
		if len(section.RootSources) == 0 {
			sb.WriteString("- (none)\n")
		} else {
			for _, entry := range section.RootSources {
				target := filepath.Join(sourcesDir, filepath.FromSlash(entry.Path))
				line := fmt.Sprintf("- %s (`%s`, `%s`)", markdownLink(indexPath, target, entry.Title), entry.SourceType, entry.SyncPolicy)
				if entry.DiscoveryState == "stale" {
					line += " `[stale]`"
				}
				sb.WriteString(line + "\n")
			}
		}
		sb.WriteString("\n")

		sb.WriteString("### Groups\n")
		if len(section.GroupIndexes) == 0 {
			sb.WriteString("- (none)\n")
		} else {
			for _, entry := range section.GroupIndexes {
				target := filepath.Join(sourcesDir, filepath.FromSlash(entry.Path))
				sb.WriteString(fmt.Sprintf("- %s — %d item(s)\n", markdownLink(indexPath, target, entry.Title), entry.Count))
			}
		}
		sb.WriteString("\n")
	}

	return os.WriteFile(indexPath, []byte(sb.String()), 0644)
}

func readMarkdownTitle(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return ""
}

func countDirectMarkdownChildren(dir string) int {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0
	}

	count := 0
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".md") || name == "INDEX.md" {
			continue
		}
		path := filepath.Join(dir, name)
		stub, err := ParseSourceStub(path)
		if err == nil && stub.Source == "notion" && stub.DiscoveryState == "stale" {
			continue
		}
		count++
	}
	return count
}
